from playwright.sync_api import Playwright, sync_playwright, expect
import time

def SignIn(playwright: Playwright, mail: str,password: str)-> None:
    browser = playwright.firefox.launch(headless=True)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.youtube.com/")
    page.get_by_role("dialog", name="Before you continue to YouTube").get_by_role("link", name="Sign in").click()
    page.wait_for_load_state()
    page.get_by_role("textbox", name="Email or phone").fill(mail)
    page.get_by_role("textbox", name="Email or phone").press("Enter")
    page.get_by_role("textbox", name="Enter your password").fill(password)
    page.get_by_role("textbox", name="Enter your password").press("Enter")
    page.wait_for_load_state()
    page.get_by_role("button", name="Create").click()
    context.storage_state(path="./data/state.json")
    context.close()
    browser.close()
def run(playwright: Playwright, file_path: str, title: str, desc: str, tags: str, minutes: float) -> None:
    browser = playwright.firefox.launch(headless=True)
    context = browser.new_context(storage_state="./data/state.json")
    page = context.new_page()
    page.goto("https://www.youtube.com/")
    page.get_by_role("button", name="Create").click()
    page.get_by_role("link", name="Upload video").get_by_role("link", name="Upload video", exact=True).filter(has_text="Upload video").click()
    page.set_input_files("input[type='file']", file_path)
    page.locator("#title-textarea").get_by_text("video", exact=True).click()
    page.locator("#title-textarea").get_by_text("video", exact=True).fill(title)
    page.locator("#description-textarea #textbox").click()
    page.locator("#description-textarea #textbox").fill(desc)
    page.get_by_role("radio", name="No, it's not 'Made for Kids'").click()
    page.get_by_role("button", name="Show more").click()
    page.get_by_placeholder("Add tag").click()
    page.get_by_placeholder("Add tag").fill(tags)
    page.get_by_placeholder("Add tag").press("Enter")
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("radio", name="Public").click()
    page.get_by_role("button", name="Publish").click()
    page.get_by_role("button", name="Close", exact=True).click()
    time.sleep(60*minutes)

    # ---------------------
    context.close()
    browser.close()
